- name: Prepare VPS for k0s
  hosts: all
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'

    - name: Add SSH key 
      copy:
        content: "{{ ssh_public_key }}"
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    - name: Update & upgrade system
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes

    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^/#/' /etc/fstab
        
    - name: Ensure journald drop-in directory exists
      ansible.builtin.file:
        path: /etc/systemd/journald.conf.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Configure journald limits
      ansible.builtin.copy:
        dest: /etc/systemd/journald.conf.d/limits.conf
        content: |
          [Journal]
          SystemMaxUse=100M
          SystemMaxFileSize=10M
          MaxRetentionSec=1day
      notify: Restart journald

  handlers:
    - name: Restart journald
      ansible.builtin.systemd:
        name: systemd-journald
        state: restarted