[INPUT]
    Name         tail
    Path         /var/www/vhosts/system/*/logs/access_ssl_log
    Path_Key     log_path
    Tag          apache.access
    DB           /var/lib/fluent-bit/apache_access.db
    Parser       apache
    Refresh_Interval 10

[FILTER]
    Name        modify
    Match       apache.access
    Add         plesk_server  acloud-6

[FILTER]
    Name         lua
    Match        apache.access
    Script       /etc/fluent-bit/scripts/add_domain.lua
    Call         add_domain

[OUTPUT]
    Name              opensearch
    Match             *
    Host              89.35.125.137
    Port              9200
    HTTP_User         fluent_bit
    HTTP_Passwd       pass
    Suppress_Type_Name   On
    Index             apache_logs
#options for test/dev only
    TLS           On
    tls.verify    Off
