@INCLUDE conf/apache.conf
@INCLUDE conf/nginx.conf
@INCLUDE conf/postfix.conf
@INCLUDE conf/dovecot.conf

[SERVICE]
    # Flush
    # =====
    # set an interval of seconds before to flush records to a destination
    flush        1

    # Daemon
    # ======
    # instruct Fluent Bit to run in foreground or background mode.
    daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # by default 'info' is set, that means it includes 'error' and 'warning'.
    log_level    info

    # Parsers File
    # ============
    # specify an optional 'Parsers' configuration file
    parsers_file parsers.conf
    parsers_file parsers/dovecot.parser.conf
    parsers_file parsers/postfix.parser.conf

    # Plugins File
    # ============
    # specify an optional 'Plugins' configuration file to load external plugins.
    plugins_file plugins.conf


    # Storage
    # =======
    # Fluent Bit can use memory and filesystem buffering based mechanisms
    #
    # - https://docs.fluentbit.io/manual/administration/buffering-and-storage
    #
    # storage metrics
    # ---------------
    # publish storage pipeline metrics in '/api/v1/storage'. The metrics are
    # exported only if the 'http_server' option is enabled.
    #
    storage.metrics on



[FILTER]
    Name        modify
    Match       *
    Add         plesk_server  plesk_server



[OUTPUT]
    Name              opensearch
    Match             apache.access*
    Host              89.35.125.137
    Port              9200
    HTTP_User         fluent_bit
    HTTP_Passwd       pass
    Suppress_Type_Name   On
    Index  apache.access-%Y.%m.%d
    #options for test/dev only
    TLS           On
    tls.verify    Off

[OUTPUT]
    Name              opensearch
    Match             apache.error
    Host              89.35.125.137
    Port              9200
    HTTP_User         fluent_bit
    HTTP_Passwd       pass
    Suppress_Type_Name   On
    Index             apache.error-%Y.%m.%d
    #options for test/dev only
    TLS           On
    tls.verify    Off


[OUTPUT]
    Name              opensearch
    Match             proxy.access*
    Host              89.35.125.137
    Port              9200
    HTTP_User         fluent_bit
    HTTP_Passwd       pass
    Suppress_Type_Name   On
    Index  proxy.access-%Y.%m.%d
    #options for test/dev only
    TLS           On
    tls.verify    Off

[OUTPUT]
    Name              opensearch
    Match             proxy.error
    Host              89.35.125.137
    Port              9200
    HTTP_User         fluent_bit
    HTTP_Passwd       pass
    Suppress_Type_Name   On
    Index             proxy.error-%Y.%m.%d
    #options for test/dev only
    TLS           On
    tls.verify    Off


[OUTPUT]
    Name              opensearch
    Match             postfix
    Host              89.35.125.137
    Port              9200
    HTTP_User         fluent_bit
    HTTP_Passwd       pass
    Suppress_Type_Name   On
    Index             postfix-%Y.%m.%d
    #options for test/dev only
    TLS           On
    tls.verify    Off

# uncomment for debug
# [OUTPUT]
#     Name   stdout
#     Match  *
#     Format json_lines
