---
- name: Install and configure Fluent Bit
  hosts: all
  become: true

  vars:
    fluentbit_repo_file: /etc/yum.repos.d/fluent-bit.repo
    fluentbit_repo_content: |
      [fluent-bit]
      name = Fluent Bit
      baseurl = https://packages.fluentbit.io/centos/$releasever/
      gpgcheck=1
      gpgkey=https://packages.fluentbit.io/fluentbit.key
      repo_gpgcheck=1
      enabled=1
    override_file: /etc/systemd/system/fluent-bit.service.d/override.conf
    override_content: |
      [Service]
      LimitNOFILE=16384
  
  vars_files:
    - vars/fluentbit.yml

  pre_tasks:
    - name: Assert required Fluent Bit variables are defined
      assert:
        that:
          - fluentbit_opensearch_host is defined
          - fluentbit_opensearch_port is defined
          - fluentbit_opensearch_password is defined
        fail_msg: |
          One or more required Fluent Bit vars are missing.
          Please set fluentbit_opensearch_host, fluentbit_opensearch_port, and fluentbit_opensearch_password.
  tasks:

    - name: Create Fluent Bit YUM repo
      copy:
        dest: "{{ fluentbit_repo_file }}"
        content: "{{ fluentbit_repo_content }}"
        owner: root
        group: root
        mode: '0644'

    - name: Install Fluent Bit
      yum:
        name: fluent-bit
        state: present

    - name: Add Fluent Bit bin path to system-wide PATH
      copy:
        dest: /etc/profile.d/fluent-bit-path.sh
        content: 'export PATH=$PATH:/opt/fluent-bit/bin'
        mode: '0755'

    - name: Create directory for Fluent Bit DB files
      file:
        path: /var/lib/fluent-bit
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure systemd override directory exists
      file:
        path: /etc/systemd/system/fluent-bit.service.d
        state: directory
        mode: '0755'

    - name: Set systemd override for Fluent Bit
      copy:
        dest: "{{ override_file }}"
        content: "{{ override_content }}"
        owner: root
        group: root
        mode: '0644'
        
    - name: Copy Fluent Bit config structure to /etc/fluent-bit/
      copy:
        src: config/
        dest: /etc/fluent-bit/
        owner: root
        group: root
        mode: '0644'
        directory_mode: '0755'
      notify: Restart fluent-bit

    - name: Deploy main fluent-bit.conf 
      template:
        src: config/fluent-bit.conf.j2
        dest: /etc/fluent-bit/fluent-bit.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart fluent-bit

    - name: Reload systemd daemon
      systemd:
        daemon_reload: true

    - name: Allow open search server in firewall
      blockinfile:
        path: /etc/csf/csf.allow.client
        marker: "# {mark} test_log_aggregation_server"
        block: |
          # test opensearch server
          tcp|in|d={{ fluentbit_opensearch_port }}|s={{ fluentbit_opensearch_host }}
          tcp|out|d={{ fluentbit_opensearch_port }}|d={{ fluentbit_opensearch_host }}
        create: yes
        owner: root
        group: root
        mode: '0644'
      notify: Reload CSF

    - name: Enable and start fluent-bit
      systemd:
        name: fluent-bit
        enabled: true
        state: started

        
    handlers:
      - name: Restart fluent-bit
        systemd:
          name: fluent-bit
          state: restarted
          
    handlers:
    - name: Reload CSF
      command: csf -r