[INPUT]
    Name         tail
    Path         /var/log/mail_log
    Path_Key     log_path
    Tag          postfix.*
    Parser       postfix
    Refresh_Interval 5
    Read_From_Head On

[FILTER]
    Name         parser
    Match        postfix.*
    Key_Name     message
    Parser       postfix_queue_id_parser
    Reserve_Data On

[FILTER]
    Name         parser
    Match        postfix.*
    Key_Name     message
    Parser       postfix_warning_parser
    Reserve_Data On

[FILTER]
    Name         parser
    Match        postfix.*
    Key_Name     message
    Parser       postfix_sasl_parser
    Reserve_Data On

[FILTER]
    Name         parser
    Match        postfix.*
    Key_Name     message
    Parser       postfix_host_ip_parser
    Reserve_Data On

[FILTER]
    Name         parser
    Match        postfix.*
    Key_Name     message
    Parser       postfix_from_to_parser
    Reserve_Data On

[FILTER]
    Name         parser
    Match        postfix.*
    Key_Name     message
    Parser       postfix_delivery_parser
    Reserve_Data On

[OUTPUT]
    Name         stdout
    Match        *
    Format       json_lines