[INPUT]
    Name         tail
    Path         /var/www/vhosts/system/*/logs/access_log
    Path_Key     log_path
    Tag          apache.access.http
    DB           /var/lib/fluent-bit/apache.access.http.db
    Parser       apache
    Refresh_Interval 10
    Skip_Long_Lines  On
    Skip_Empty_Lines On

[INPUT]
    Name         tail
    Path         /var/www/vhosts/system/*/logs/access_https_log
    Path_Key     log_path
    Tag          apache.access.https
    DB           /var/lib/fluent-bit/apache.access.https.db
    Parser       apache
    Refresh_Interval 10
    Skip_Long_Lines  On
    Skip_Empty_Lines On

[INPUT]
    Name         tail
    Path         /var/www/vhosts/system/*/logs/error_log
    Path_Key     log_file
    Tag          apache.error
    DB           /var/lib/fluent-bit/apache.error.db
    Parser       apache_error
    Refresh_Interval 10 



[FILTER]
    Name        modify
    Match       *
    Add         plesk_server  acloud-6

[FILTER]
    Name         add_site_domain
    Match        *
    Script       /etc/fluent-bit/scripts/add_site_domain.lua
    Call         add_domain

[FILTER]
    Name        modify
    Match       apache.access.https
    Add         log.type     https.access
    Add         protocol     https

[FILTER]
    Name        modify
    Match       apache.access.http
    Add         log.type     http.access
    Add         protocol     http

[FILTER]
    Name        modify
    Match       apache.error
    Add         log.type     apache.error
