[INPUT]
    Name              tail
    Path              /var/log/mail_log
    Parser            dovecot
    Tag               dovecot.raw
    Refresh_Interval  5
    Skip_Long_Lines   On

[FILTER]
    Name    parser
    Match   dovecot.raw
    Key_Name message
    Parser  dovecot_login
    Reserve_Data On

[FILTER]
    Name    parser
    Match   dovecot.raw
    Key_Name message
    Parser  dovecot_login_disconnect
    Reserve_Data On

[FILTER]
    Name    parser
    Match   dovecot.raw
    Key_Name message
    Parser  dovecot_login_truncated
    Reserve_Data On

[FILTER]
    Name    parser
    Match   dovecot.raw
    Key_Name message
    Parser  dovecot_lda_service
    Reserve_Data On

[FILTER]
    Name    parser
    Match   dovecot.raw
    Key_Name message
    Parser  dovecot_service_disconnect
    Reserve_Data On

[FILTER]
    Name    parser
    Match   dovecot.raw
    Key_Name message
    Parser  dovecot_login_any
    Reserve_Data On

[FILTER]
    Name    parser
    Match   dovecot.raw
    Key_Name message
    Parser  dovecot_disconnect_any
    Reserve_Data On