[INPUT]
    Name              tail
    Path              /var/log/mail_log
    Parser            postfix
    Tag               postfix.*
    Refresh_Interval  5
    Skip_Long_Lines   On
    DB           /var/lib/fluent-bit/postfix.db
    #debug option
    #Read_from_Head    On

[FILTER]
    Name    lua
    Match   postfix.*
    Script  /etc/fluent-bit/scripts/postfix_parser.lua
    Call    postfix_parse


