[INPUT]
    Name         tail
    Path         /var/www/vhosts/system/*/logs/access_log
    Path_Key     log_path
    Tag          apache.access.http
    DB           /var/lib/fluent-bit/apache.access.http.db
    Skip_Empty_Lines On
    #debug option
    #Read_from_Head    On
    Parser    apache_custom

[INPUT]
    Name         tail
    Path         /var/www/vhosts/system/*/logs/access_ssl_log.processed
    Path_Key     log_path
    Tag          apache.access.https
    DB           /var/lib/fluent-bit/apache.access.https.db
    Skip_Empty_Lines On
    #debug option
    #Read_from_Head    On
    Parser    apache_custom

[INPUT]
    Name         tail
    Path         /var/www/vhosts/system/*/logs/error_log
    Path_Key     log_path
    Tag          apache.error
    DB           /var/lib/fluent-bit/apache.error.db
    Parser       apache_error
    #debug option
    #Read_from_Head    On


[FILTER]
    Name        modify
    Match       apache.access.https
    Add         protocol     https

[FILTER]
    Name        modify
    Match       apache.access.http
    Add         protocol     http

[FILTER]
    Name        modify
    Match       apache.error
    Add         log_type     apache.error


[FILTER]
    Name    grep
    Match   apache.error
    Exclude message "PHP Notice"
    Exclude message "Order properties should not be accessed directly"

#drop static assets requests
[FILTER]
    Name    grep
    Match   apache.*
    Exclude path \.(css|js|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot|webp)(\?.*)?$


[FILTER]
    Name         lua
    Match        *
    Script       /etc/fluent-bit/scripts/add_site_domain.lua
    Call         add_domain

#drop message by site domain if it occurs more than 500 times in 60s window check every 5 s
[FILTER]
    Name         lua
    Match        apache.error
    Script       /etc/fluent-bit/scripts/apache.error.throttle_by_domain_key.lua
    Call         throttle_by_key

