[INPUT]
    Name              tail
    Path              /var/log/mail_log
    Parser            syslog-rfc3164
    Tag               dovecot
    DB           /var/lib/fluent-bit/dovecot.db
    Skip_Long_Lines   On
    #debug option
    #Read_from_Head    On

[FILTER]
    Name    parser
    Match   dovecot
    Key_Name message
    Parser  dovecot_login
    Reserve_Data On

[FILTER]
    Name    parser
    Match   dovecot
    Key_Name message
    Parser  dovecot_login_disconnect
    Reserve_Data On


[FILTER]
    Name    parser
    Match   dovecot
    Key_Name message
    Parser  dovecot_lda_service
    Reserve_Data On

#throttle inotify warn messages
[FILTER]
    Name      rewrite_tag
    Match     dovecot
    Rule      message  Inotify.*  dovecot.inotify.warn  true


[FILTER]
    Name      throttle
    Match     dovecot.inotify.warn
    Rate      1
    Window    300
    Interval  60