[INPUT]
    Name              tail
    Path              /var/log/mail_log
    Parser            syslog-rfc3164-nopri
    Tag               mail
    DB           /var/lib/fluent-bit/dovecot.db
    Skip_Long_Lines   On
    #debug option
    #Read_from_Head    On


[FILTER]
    Name      rewrite_tag
    Match     mail
    Rule      ident ^dovecot(-\w+)?$  dovecot  true

# drop clean disconnects
[FILTER]
    Name    grep
    Match   dovecot
    Exclude message ^.*(Logged out|Connection closed).*

[FILTER]
    Name    parser
    Match   dovecot
    Key_Name message
    Parser  dovecot_login
    Reserve_Data On

[FILTER]
    Name    parser
    Match   dovecot
    Key_Name message
    Parser  dovecot_login_disconnect
    Reserve_Data On


[FILTER]
    Name    parser
    Match   dovecot
    Key_Name message
    Parser  dovecot_lda_saved
    Reserve_Data On


[FILTER]
    Name    parser
    Match   dovecot
    Key_Name message
    Parser  dovecot_lda_sieve
    Reserve_Data On


[FILTER]
    Name    parser
    Match   dovecot
    Key_Name message
    Parser  dovecot_warning
    Reserve_Data On

#throttle inotify warn messages
[FILTER]
    Name      rewrite_tag
    Match     dovecot
    Rule      message  Inotify.*  dovecot.inotify.warn  true


#drop message by site domain if it occurs more than 100 times in 60s window check every 5 s
[FILTER]
    Name         lua
    Match        apache.error
    Script       /etc/fluent-bit/scripts/dovecot.throttle_by_message_key.lua
    Call         throttle_by_key

[FILTER]
    Name   lua
    Match  dovecot
    Script /etc/fluent-bit/scripts/local_to_utc.lua
    Call   adjust_to_utc
