[INPUT]
    Name              tail
    Path              /var/log/mail_log
    Parser            syslog-rfc3164-nopri
    Tag               mail
    DB           /var/lib/fluent-bit/dovecot.db
    Skip_Long_Lines   On
    #debug option
    #Read_from_Head    On


[FILTER]
    Name      rewrite_tag
    Match     mail
    Rule      ident ^dovecot(-\w+)?$  dovecot  true

# drop clean disconnects
[FILTER]
    Name    grep
    Match   dovecot
    Exclude message ^.*(Logged out|Connection closed).*

[FILTER]
    Name    parser
    Match   dovecot
    Key_Name message
    Parser  dovecot_login
    Reserve_Data On

[FILTER]
    Name    parser
    Match   dovecot
    Key_Name message
    Parser  dovecot_login_disconnect
    Reserve_Data On


[FILTER]
    Name    parser
    Match   dovecot
    Key_Name message
    Parser  dovecot_lda_service
    Reserve_Data On

#throttle inotify warn messages
[FILTER]
    Name      rewrite_tag
    Match     dovecot
    Rule      message  Inotify.*  dovecot.inotify.warn  true


[FILTER]
    Name      throttle
    Match     dovecot.inotify.warn
    Rate      1
    Window    300
    Interval  60

[FILTER]
    Name   lua
    Match  dovecot
    Script /etc/fluent-bit/scripts/local_to_utc.lua
    Call   adjust_to_utc