[INPUT]
    Name         tail
    Path         /var/www/vhosts/system/*/logs/proxy_access_log
    Path_Key     log_path
    Tag          proxy.access.http
    DB           /var/lib/fluent-bit/proxy.access.http.db
    Parser       nginx
    Skip_Long_Lines  On
    Skip_Empty_Lines On
    #debug option
    #Read_from_Head    On

[INPUT]
    Name         tail
    Path         /var/www/vhosts/system/*/logs/proxy_access_ssl_log
    Path_Key     log_path
    Tag          proxy.access.https
    DB           /var/lib/fluent-bit/proxy.access.https.db
    Parser       nginx
    Skip_Long_Lines  On
    Skip_Empty_Lines On
    #debug option
    #Read_from_Head    On

[INPUT]
    Name         tail
    Path         /var/www/vhosts/system/*/logs/proxy_error_log
    Path_Key     log_path
    Tag          proxy.error
    DB           /var/lib/fluent-bit/proxy.error.db
    Parser       nginx_error
    #debug option
    #Read_from_Head    On

#drop static assets requests
[FILTER]
    Name    grep
    Match   apache.*
    Exclude path \.(css|js|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot|webp)(\?.*)?$

[FILTER]
    Name        modify
    Match       proxy.access.http
    Add         protocol     http

[FILTER]
    Name        modify
    Match       proxy.access.https
    Add         protocol     https

[FILTER]
    Name        modify
    Match       proxy.error
    Add         log_type     proxy.error

[FILTER]
    Name         lua
    Match        *
    Script       /etc/fluent-bit/scripts/add_site_domain.lua
    Call         add_domain
