[INPUT]
    Name         tail
    Path         /var/www/vhosts/system/*/logs/proxy_access_log
    Path_Key     log_path
    Tag          proxy.access.http
    DB           /var/lib/fluent-bit/proxy.access.http.db
    Parser       nginx
    Skip_Long_Lines  On
    Skip_Empty_Lines On
    #debug option
    #Read_from_Head    On

[INPUT]
    Name         tail
    Path         /var/www/vhosts/system/*/logs/proxy_access_https_log
    Path_Key     log_path
    Tag          proxy.access.https
    DB           /var/lib/fluent-bit/proxy.access.https.db
    Parser       nginx
    Skip_Long_Lines  On
    Skip_Empty_Lines On
    #debug option
    #Read_from_Head    On

[INPUT]
    Name         tail
    Path         /var/www/vhosts/system/*/logs/proxy_error_log
    Path_Key     log_path
    Tag          proxy.error
    DB           /var/lib/fluent-bit/proxy.error.db
    Parser       nginx_error
    #debug option
    #Read_from_Head    On




[FILTER]
    Name        modify
    Match       proxy.access.http
    Add         log_type     proxy.http.access
    Add         protocol     http

[FILTER]
    Name        modify
    Match       proxy.access.https
    Add         log_type     proxy.https.access
    Add         protocol     https

[FILTER]
    Name        modify
    Match       proxy.error
    Add         log_type     proxy.error

[FILTER]
    Name         lua
    Match        *
    Script       /etc/fluent-bit/scripts/add_site_domain.lua
    Call         add_domain
