[INPUT]
    Name              tail
    Path              /var/log/mail_log
    Tag               postfix.send
    Skip_Long_Lines   On
    DB           /var/lib/fluent-bit/postfix.db
    #debug option
    #Read_from_Head    On

[FILTER]
    Name      rewrite_tag
    Match     postfix.send
    Rule      log  ".*SASL (?:LOGIN )?authentication failed.*" postfix.auth  false

[FILTER]
    Name       parser
    Match      postfix.send
    Parser     postfix
    Key_Name log

[FILTER]
    Name    lua
    Match   postfix.send
    Script  /etc/fluent-bit/scripts/postfix_parser.lua
    Call    postfix_parse


[FILTER]
    Name       parser
    Match      postfix.auth
    Parser     postfix_auth
    Key_Name log

[FILTER]
    Name   modify
    Match  postfix.auth
    Add    auth_error "SASL LOGIN authentication failed: authentication failure"
    
[FILTER]
    Name   lua
    Match  postfix.auth
    Script /etc/fluent-bit/scripts/local_to_utc.lua
    Call   adjust_to_utc
