[INPUT]
    Name         tail
    Path         /var/log/secure
    Path_Key     log_path
    Tag          secure
    DB           /var/lib/fluent-bit/secure.db
    Skip_Empty_Lines On
    Parser  syslog-rfc3164-nopri
    #debug option
    #Read_from_Head    On


[FILTER]
    Name rewrite_tag
    Match secure
    Rule $ident sshd secure.sshd false

[FILTER]
    Name    parser
    Match   secure.sshd
    Key_Name message
    Parser  sshd_login
    Reserve_Data On

[FILTER]
    Name    parser
    Match   secure.sshd
    Key_Name message
    Parser  sshd_key_accepted
    Reserve_Data On

[FILTER]
    Name    parser
    Match   secure.sshd
    Key_Name message
    Parser  sshd_password_accepted    
    Reserve_Data On

[FILTER]
    Name    parser
    Match   secure.sshd
    Key_Name message
    Parser  sshd_disconnect
    Reserve_Data On

[FILTER]
    Name    parser
    Match   secure.sshd
    Key_Name message
    Parser  sshd_disconnected_user
    Reserve_Data On

[FILTER]
    Name    parser
    Match   secure.sshd
    Key_Name message
    Parser  sshd_session_closed
    Reserve_Data On
    
[FILTER]
    Name   lua
    Match  secure.sshd
    Script /etc/fluent-bit/scripts/local_to_utc.lua
    Call   adjust_to_utc