[PARSER]
    Name        apache_custom
    Format      regex
    Regex       ^(?<host>[^\s\n\r]+)\s+\S+\s+(?<user>\S+)\s+\[(?<time>[^\]]+)\]\s+"(?<request>[^"]*?)"\s+(?<code>\d+)\s+(?<size>\S+)\s+"(?<referer>[^"]*)"\s+"(?<agent>[^"]*)"
    Time_Key    time
    Time_Format %d/%b/%Y:%H:%M:%S %z
