[PARSER]
    Name        dovecot_login
    Format      regex
    Regex       ^(?<service>\w+)-login:\s+Login:\s+user=<(?<user>[^>]*)>,\s+method=(?<method>\w+),\s+rip=(?<remote_ip>[^,]+),\s+lip=(?<local_ip>[^,]+),\s+mpid=(?<mail_pid>\d+)(?:,\s*(?<security>\w+))?(?:,\s*session=<(?<session_id>[^>]*)>?)?

[PARSER]
    Name        dovecot_login_disconnect
    Format      regex
    Regex       ^(?<service>\w+)-login:\s+Disconnected:\s+(?<disconnect_reason>(?!(Logged out|Connection closed)).*):\s+user=<(?<user>[^>]*)>,\s+rip=(?<remote_ip>[^,]+),\s+lip=(?<local_ip>[^,]+)(?:,\s+(?<tls_info>[^,]+))?(?:,\s+session=<(?<session_id>[^>]*)>)?


[PARSER]
    Name        dovecot_lda_service
    Format      regex
    Regex       ^service=(?<service>\w+),\s+user=(?<user>[^,]+),\s+ip=\[(?<ip>[^\]]*)\](?:\.\s+msgid=<(?<message_id>[^>]+)>)?:\s+(?<action>.*)$

