[PARSER]
    Name        syslog-rfc3164-nopri
    Format      regex
    Regex       /^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/
    Time_Key    time
    Time_Format %b %d %H:%M:%S
    Time_Keep   On


[PARSER]
    Name        dovecot_login
    Format      regex
    Regex       ^(?<service>\w+)-login:\s+Login:\s+user=<(?<user>[^>]*)>,\s+method=(?<method>[^,]+),\s+rip=(?<remote_ip>[^,]+),\s+lip=(?<local_ip>[^,]+)(?:,\s*mpid=(?<mail_pid>\d+))?(?:,\s*(?<security>TLS|session))?(?:,\s*session=<(?<session_id>[^>]*)>)?.*$

[PARSER]
    Name        dovecot_login_disconnect
    Format      regex
    Regex       ^(?<service>\w+)-login:\s+Disconnected:\s+(?<disconnect_reason>.*):\s+user=<(?<user>[^>]*)>,\s*(?:method=(?<method>[^,]+),\s*)?rip=(?<remote_ip>[^,]+),\s*lip=(?<local_ip>[^,]+)(?:,\s*session=<(?<session_id>[^>]*)>)?.*$

[PARSER]
    Name        dovecot_warning
    Format      regex
    Regex       ^service=(?<service>\w+),\s+user=(?<user>[^,]+),\s+ip=\[(?<ip>[^\]]*)\]\.\s+Warning:\s+(?<warning>.*)$

[PARSER]
    Name        dovecot_lda_saved
    Format      regex
    Regex       ^service=(?<service>\w+),\s+user=(?<user>[^,]+),\s+ip=\[(?<ip>[^\]]*)\]\.\s+msgid=(?<msgid>[^:]+):\s+(?<action>saved mail)\s+to\s+(?<mailbox>\w+)$

[PARSER]
    Name        dovecot_lda_sieve
    Format      regex
    Regex       ^service=lda,\s+user=(?<user>[^,]+),\s+ip=\[(?<ip>[^\]]*)\]\.\s+sieve:\s+msgid=(?:<(?<msgid>[^>]+)>|(?<msgid>\S+)):\s+(?<action>stored mail) into mailbox '(?<mailbox>[^']+)'$

[PARSER]
    Name        dovecot_lda_sieve_redirect
    Format      regex
    Regex       ^service=lda,\s+user=(?<user>[^,]+),\s+ip=\[(?<ip>[^\]]*)\]\.\s+sieve:\s+msgid=(?:<(?<msgid>[^>]+)>|(?<msgid>\S+)):\s+(?<action>redirect action):\s+forwarded to\s+<(?<recipient>[^>]+)>$

[PARSER]
    Name        dovecot_error
    Format      regex
    Regex       ^service=(?<service>[^,]+),\s+user=(?<user>[^,]+),\s+ip=\[(?<ip>[^\]]+)\]\.\s+Error:\s+(?<error_msg>.*)$

[PARSER]
    Name        dovecot_service_disconnect
    Format      regex
    Regex       ^service=(?<service>[^,]+),\s+user=(?<user>[^,]+),\s+ip=\[(?<ip>[^\]]+)\]\.\s+Disconnected:\s+(?<disconnect_reason>.*?)\s+rcvd=(?<rcvd>\d+),\s+sent=(?<sent>\d+)$
