[PARSER]
    Name        postfix
    Format      regex
    Regex       ^(?<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+(?<hostname>\S+)\s+(?<service>[^\[]+)\[(?<pid>\d+)\]:\s+(?:(?<queue_id>[^:]+):\s+)?(?<message>.*)$