[PARSER]
    Name        postfix
    Format      regex
    Regex       ^(?<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+(?<hostname>\S+)\s+(?<service>[^\[]+)\[(?<pid>\d+)\]:\s+(?:(?<queue_id>[^:]+):\s+)?(?<message>.*)$


[PARSER]
    Name        postfix_auth
    Format      regex
    Regex       ^(?<auth_timestamp>\w+ \d+ \d+:\d+:\d+) (?<auth_host>\S+) (?<auth_process>postfix\/\S+)\[(?<auth_pid>\d+)\]: (?<auth_level>\w+): (?<auth_remote_host>[^\[]+)\[(?<auth_remote_ip>[^\]]+)\]: SASL LOGIN authentication failed: authentication failure(?:, sasl_username=(?<auth_username>\S+))?$
    Time_Key    timestamp
    Time_Format %b %d %H:%M:%S

