[PARSER]
    Name        sshd_login
    Format      regex
    Regex       (?<sshd_event>[^ ]+ [^ ]+) for user (?<user>\S+) by \(uid=(?<uid>\d+)\)
    Time_Key    time
    Time_Format %b %d %H:%M:%S

[PARSER]
    Name        sshd_key_accepted
    Format      regex
    Time_Key    time
    Time_Format %b %d %H:%M:%S
    Regex       ^(?<sshd_event>Accepted publickey)\sfor\s(?<user>\S+)\sfrom\s(?<ip>\S+)\sport\s(?<port>\d+)\s(?<protocol>\S+):\s(?<key>.+)$


[PARSER]
    Name        sshd_password_accepted
    Format      regex
    Time_Key    time
    Time_Format %b %d %H:%M:%S
    Regex       ^(?:\s+\S+\s+sshd\[\d+\]:\s)?Accepted\s(?<auth_type>\S+)\sfor\s(?<user>\S+)\sfrom\s(?<ip>\S+)\sport\s(?<port>\d+)\s(?<protocol>\S+)?$

[PARSER]
    Name        sshd_disconnect
    Format      regex
    Regex       ^(?<sshd_event>Disconnected from)(?: user (?<user>\S+))? (?<ip>\S+) port (?<port>\d+)$

[PARSER]
    Name        sshd_disconnected_user
    Format      regex
    Regex       ^(?<sshd_event>Disconnected from user) (?<user>\S+)\s(?<ip>\S+)\sport\s(?<port>\d+)$

[PARSER]
    Name        sshd_session_closed
    Format      regex
    Regex       pam_unix\(sshd:session\): (?<sshd_event>session closed) for user (?<user>\S+)$

[PARSER]
    Name        sshd_disconnect_by_user
    Format      regex
    Regex       ^Received disconnect from (?<ip>\S+) port (?<port>\d+):.*: (?<sshd_event>.+)$