[PARSER]
    Name        sshd_event
    Format      regex
    Regex       ^(?<event_type>Accepted publickey|Disconnected from user|session opened for user|session closed for user) (?<user>\S+)? ?(?<ip>\S+)? 
    Time_Key    time
    Time_Format %b %d %H:%M:%S