- name: Prepare host to be warpgate target
  become: yes
  strategy: free
  hosts: access_targets
  vars:
    username: "CHANGE_THIS"
    user_pass: "CHANGE_THIS"
    user_ssh_pubkey: "CHANGE_THIS"


  tasks:
    - name: Fail if username is not set
      fail:
        msg: "You must set 'username'"
      when: username | default("CHANGE_THIS") == "CHANGE_THIS"

    - name: Fail if user_pass is not set
      fail:
        msg: "You must set 'username'"
      when: user_pass  | default("CHANGE_THIS") == "CHANGE_THIS"

    - name: Fail if user_ssh_pubkey is not set
      fail:
        msg: "You must set 'user_ssh_pubkey'"
      when: user_ssh_pubkey | default("CHANGE_THIS") == "CHANGE_THIS"

    - name: Ensure user exists
      user:
        name: "{{ username }}"
        shell: /bin/bash
        create_home: yes
        password: "{{ 'YourStrongPassword' | password_hash('sha512') }}"
        update_password: on_create

    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'

    - name: Add user ssh key 
      authorized_key:
        user: "{{ username }}"
        exclusive: true
        key: "{{ user_ssh_pubkey }}"

    - name: Harden sshd config
      ansible.builtin.copy:
        src: ./templates/sshd_config.mozilla
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'

    - name: Restart SSH
      ansible.builtin.systemd:
        name: ssh
        state: restarted
        daemon_reload: yes