[PARSER]
    Name        postfix
    Format      regex
    Regex       ^(?<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+(?<hostname>\S+)\s+(?<service>[^\[]+)\[(?<pid>\d+)\]:\s+(?:(?<queue_id>[^:]+):\s+)?(?<message>.*)$
    Time_Key    timestamp
    Time_Format %b %d %H:%M:%S
    Time_Keep   On