- name: Set up restricted automation user with dispatcher binary
  hosts: backend_servers
  become: yes
  vars:
    username: secops
    app_name: secOpsDispatcher
    app_url: https://github.com/HossBigft/sysAdminToolboxBackendTokenExecutor/releases/latest/download/secOpsDispatcher
    backend_user_ssh_pubkey: "CHANGE_THIS"

  tasks:
    - name: Fail if backend_user_ssh_pubkey is not set
      fail:
        msg: "You must set 'backend_user_ssh_pubkey'"
      when: backend_user_ssh_pubkey == "CHANGE_THIS"

    - name: Ensure user exists
      user:
        name: "{{ username }}"
        shell: /bin/bash
        group: wheel
        create_home: yes

    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'

    - name: Copy signed executor binary from local machine
      copy:
        src: "./secOpsDispatcher"
        dest: "/home/{{ username }}/{{ app_name }}"
        mode: '0700'
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Add serverkit backend ssh key with restrictions
      authorized_key:
        user: "{{ username }}"
        key: "{{ backend_user_ssh_pubkey }}"
        key_options: 'command="sudo /home/{{ username }}/{{ app_name }}",no-pty,no-port-forwarding,no-agent-forwarding,no-X11-forwarding'

    - name: Init signed executor
      command: "/home/{{ username }}/{{ app_name }} init"
      register: init_output

    - name: Print signed executor response
      debug:
        var: init_output.stdout

    - name: Copy pub.key to .secOpsDispatcher
      copy:
        src: "./pub.key"
        dest: "/home/{{ username }}/.secOpsDispatcher/pub.key"
        owner: "root"
        group: "root"
        mode: '0600'
