- name: Ensure test database exists
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    state: present
    login_host: "{{ pg_host }}"
    port: "{{ pg_port }}"
    login_user: "{{ pg_admin_user }}"
    login_password: "{{ pg_admin_password }}"

- name: Ensure read-only role exists
  community.postgresql.postgresql_user:
    name: "{{ db_role }}"
    password: "{{ db_role_password }}"
    role_attr_flags: "LOGIN"
    state: present
    login_host: "{{ pg_host }}"
    port: "{{ pg_port }}"
    login_user: "{{ pg_admin_user }}"
    login_password: "{{ pg_admin_password }}"

- name: Grant CONNECT on database
  community.postgresql.postgresql_privs:
    db: "{{ db_name }}"
    role: "{{ db_role }}"
    type: database
    privs: connect
    state: present
    login_host: "{{ pg_host }}"
    port: "{{ pg_port }}"
    login_user: "{{ pg_admin_user }}"
    login_password: "{{ pg_admin_password }}"

- name: Get list of user schemas
  community.postgresql.postgresql_query:
    db: "{{ db_name }}"
    login_host: "{{ pg_host }}"
    login_port: "{{ pg_port  }}"
    login_user: "{{ pg_admin_user }}"
    login_password: "{{ pg_admin_password }}"
    query: |
      SELECT nspname 
      FROM pg_namespace 
      WHERE nspname NOT LIKE 'pg_%' 
        AND nspname != 'information_schema'
  register: schema_list

- name: Ensure user has USAGE on all schemas
  community.postgresql.postgresql_privs:
    db: "{{ db_name }}"
    login_host: "{{ pg_host }}"
    login_port: "{{ pg_port }}"
    login_user: "{{ pg_admin_user }}"
    login_password: "{{ pg_admin_password }}"
    role: "{{ pg_admin_user }}"
    objs: "{{ item.nspname }}"
    type: schema
    privs: USAGE
    state: present
  loop: "{{ schema_list.query_result }}"

- name: Grant SELECT on all existing tables
  community.postgresql.postgresql_privs:
    db: "{{ db_name }}"
    role: "{{ db_role }}"
    type: table
    objs: ALL_IN_SCHEMA
    privs: select
    state: present
    login_host: "{{ pg_host }}"
    port: "{{ pg_port }}"
    login_user: "{{ pg_admin_user }}"
    login_password: "{{ pg_admin_password }}"

- name: Set default privileges for future tables
  community.postgresql.postgresql_privs:
    db: "{{ db_name }}"
    role: "{{ db_role }}"
    type: default_privs
    objs: tables
    schema: public
    privs: select
    state: present
    grant_option: no
    login_host: "{{ pg_host }}"
    port: "{{ pg_port }}"
    login_user: "{{ pg_admin_user }}"
    login_password: "{{ pg_admin_password }}"